export const theme = {
    accent: "#cac1ec",
    accent50: "rgba(205, 184, 150, 0.5)",
    background: "#0c0b0f",
    border: "#3a3a4e",
    card: "#211f24",
    muted: "#8b85a1",
    muted10: "rgba(131, 118, 96, 0.1)",
    muted20: "rgba(131, 118, 96, 0.2)",
    muted30: "rgba(131, 118, 96, 0.3)",
    primary: "oklch(0.923 0.003 48.717)",
};
export const styles = {
    stepsContainer: {
        display: "flex",
        flexDirection: "column",
        fontSize: "0.875rem",
        fontWeight: 600,
        color: theme.accent50,
        alignSelf: "center",
        width: "66.6667%",
        height: "2.5rem",
    },
    stepsRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.25rem",
        width: "100%",
        height: "100%",
    },
    progressFill: {
        backgroundColor: theme.accent,
        height: "1.25rem",
        borderTopLeftRadius: "0.125rem",
        borderBottomLeftRadius: "0.125rem",
        borderTopRightRadius: "0.0625rem",
        borderBottomRightRadius: "0.0625rem",
        transition: "min-width 200ms",
    },
    progressTick: {
        minWidth: "0.25rem",
        minHeight: "2rem",
        backgroundColor: theme.accent,
        borderRadius: "0.125rem",
    },
    progressRemaining: {
        width: "100%",
        height: "1.2rem",
        backgroundColor: theme.muted10,
        borderTopLeftRadius: "0.0625rem",
        borderBottomLeftRadius: "0.0625rem",
        borderTopRightRadius: "0.125rem",
        borderBottomRightRadius: "0.125rem",
    },
    stepsLabelsRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "0.25rem",
        marginTop: "-1.1875rem",
        width: "100%",
        height: "100%",
    },
    stepLabelLeft: {
        transform: "translateX(-100%)",
        marginLeft: "-0.375rem",
        transition: "color 200ms",
    },
    stepLabelRight: {
        transform: "translateX(100%)",
        marginRight: "-1rem",
        transition: "color 200ms",
    },
    stepsDividerRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        width: "100%",
        justifyContent: "space-evenly",
    },
    stepColumn: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 200ms",
    },
    playlistDividerRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        width: "100%",
    },
    playlistSpacerLeft: {
        width: "28.5714%",
    },
    playlistSpacerRight: {
        width: "42.8571%",
    },
    playlistStepColumnLeft: {
        display: "flex",
        flexDirection: "column",
        width: 0,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: "-0.1875rem",
        transition: "color 200ms",
    },
    playlistStepColumnRight: {
        display: "flex",
        flexDirection: "column",
        width: 0,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: "-0.9375rem",
        transition: "color 200ms",
    },
    nowrap: {
        whiteSpace: "nowrap",
    },
    card: {
        position: "fixed",
        borderBottom: `1px solid ${theme.border}`,
        borderLeft: `1px solid ${theme.border}`,
        borderBottomLeftRadius: "0.5rem",
        top: 0,
        right: 0,
        width: "30rem",
        height: "40rem",
        background: `linear-gradient(180deg, ${theme.card}ee 0%, ${theme.background}dd 20%, #000000cc 100%)`,
        display: "flex",
        flexDirection: "column",
    },
    controlButton: {
        borderRadius: "9999px",
        width: "2rem",
        height: "2rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "1.125rem",
        border: "none",
        color: "inherit",
        cursor: "pointer",
    },
    cardBody: {
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: "1rem",
    },
};